example_node:
  ros__parameters:
    task_priority_solver:
      end_effector_frame_id: alpha_tcp
      constrained_joints:
        - alpha_axis_d
        - alpha_axis_e
      end_effector_pose_task:
        gain: 0.3
      joint_limit_task:
        alpha_axis_d:
          safety_tolerance: 0.78539816
          activation_threshold: 0.087
          gain: 0.2
        alpha_axis_e:
          safety_tolerance: 0.78539816
          activation_threshold: 0.087
          gain: 0.2
