controller_manager:
  ros__parameters:
    update_rate: 225 # Hz

    integral_sliding_mode_controller:
      type: velocity_controllers/IntegralSlidingModeController

integral_sliding_mode_controller:
  ros__parameters:
    dof_names:
      - "x"
      - "y"
      - "z"
      - "rx"
      - "ry"
      - "rz"
    gains:
      rho: 20.0
      lambda: 200.0
      Kp: [10.0, 10.0, 6.0, 3.0, 6.0, 10.0]
    hydrodynamics:
      mass: 13.5
      weight: 114.80
      buoyancy: 112.80
      moments_of_inertia: [0.16, 0.16, 0.16]
      added_mass: [-5.50, -12.70, -14.60, -0.12, -0.12, -0.12]
      center_of_buoyancy: [0.0, 0.0, 0.0]
      center_of_gravity: [0.0, 0.0, 0.0]
      linear_damping: [-4.03, -6.22, -5.18, -0.07, -0.07, -0.07]
      quadratic_damping: [-18.18, -21.66, -36.99, -1.55, -1.55, -1.55]
